# Generated by Django 4.2.7 on 2023-11-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0004_alter_countrytaxesconcept_rate_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='description',
        ),
    ]
