# Generated by Django 4.2.7 on 2023-11-11 13:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('concept', '0005_remove_tax_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
